package:
  name: cert-manager-cmctl
  # This got pulled from the cert-manager repo in the 1.15 release, prior to
  # that it was in the cert-manager/cert-manager repo.
  version: 2.1.0
  epoch: 4
  description: Automatically provision and manage TLS certificates in Kubernetes
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - cmctl=${{package.full-version}}

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 6c5d929acaf768c40d9b8ede807fdc761919a492
      repository: https://github.com/cert-manager/cmctl
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: google.golang.org/grpc@v1.64.1 oras.land/oras-go@v1.2.6 github.com/docker/docker@v27.1.1

  - uses: go/build
    with:
      packages: main.go
      output: cmctl
      ldflags: -X github.com/cert-manager/cmctl/pkg/util.AppVersion=$(git describe --tags --always --match='v*' --abbrev=14 --dirty) -X github.com/cert-manager/cmctl/pkg/util.AppGitCommit=$(git rev-parse HEAD)

update:
  enabled: true
  github:
    identifier: cert-manager/cmctl
    strip-prefix: v
    tag-filter: v
    use-tag: true

test:
  pipeline:
    - runs: |
        cmctl -h
