package:
  name: coredns
  version: 1.11.3
  epoch: 6
  description: CoreDNS is a DNS server that chains plugins
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - libcap-utils
      - make

pipeline:
  - uses: git-checkout
    with:
      expected-commit: a7ed346585e30b99317d36e4d007b7b19a228ea5
      repository: https://github.com/coredns/coredns
      tag: v${{package.version}}

  - runs: |
      # Generate code and fetch plugins
      make gen

  - uses: go/build
    with:
      ldflags: -X github.com/coredns/coredns/coremain.GitCommit=v${{package.version}}
      output: coredns
      packages: .

  - runs: setcap cap_net_bind_service=+ep "${{targets.contextdir}}/usr/bin/coredns"

subpackages:
  - name: kuma-coredns
    description: CoreDNS with plugins used by Kuma
    pipeline:
      - runs: |
          # Build with plugins used by Kuma
          # Plugin list: https://github.com/kumahq/coredns-builds/blob/main/plugin.cfg
          mv kuma-plugin.cfg plugin.cfg
          # Generate code and fetch plugins
          make gen
      - uses: go/build
        with:
          ldflags: -X github.com/coredns/coredns/coremain.GitCommit=v${{package.version}}
          output: coredns
          packages: .
    test:
      pipeline:
        - runs: |
            coredns -version
            coredns -plugins

update:
  enabled: true
  github:
    identifier: coredns/coredns
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - bind-tools
  pipeline:
    - runs: |
        coredns -version
        coredns -plugins
    - runs: |
        cat > Corefile <<EOF
        .:1053 {
            file /home/build/db.wolfi.dev
            log
            errors
            cache
        }
        EOF

        cat > /home/build/db.wolfi.dev <<'EOF'
        $TTL 3600
        @    IN SOA ns1.wolfi.dev. admin.wolfi.dev. (
                  20240101   ; Serial
                  7200       ; Refresh
                  3600       ; Retry
                  1209600    ; Expire
                  3600 )     ; Negative Cache TTL
        ;
        @    IN NS  ns1.wolfi.dev.
        ;
        foo.wolfi.dev  IN TXT "hi"
        EOF

        coredns &
        sleep 2

        # validates intree plugins can be successfully loaded
        dig @localhost -p 1053 foo.wolfi.dev TXT +short | grep -q '"hi"'
