package:
  name: cri-tools
  version: 1.30.1
  epoch: 3
  description: CLI and validation tools for Kubelet Container Runtime Interface (CRI) .
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      expected-commit: b633b386d6ec2c5743999a56c7df332b43759f9a
      repository: https://github.com/kubernetes-sigs/cri-tools
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.46.0 github.com/docker/docker@v26.1.5
      replaces: k8s.io/kubernetes=k8s.io/kubernetes@v1.30.3 k8s.io/apiserver=k8s.io/apiserver@v0.30.3 k8s.io/apimachinery=k8s.io/apimachinery@v0.30.3 k8s.io/client-go=k8s.io/client-go@v0.30.3

  - uses: go/build
    with:
      ldflags: -s -w -X github.com/kubernetes-sigs/cri-tools/pkg/version.VERSION=${{package.version}}
      output: crictl
      packages: ./cmd/crictl

  - runs: |
      make critest
      install -Dm755 build/bin/linux/**/critest "${{targets.destdir}}"/usr/bin/critest

  - uses: strip

subpackages:
  - name: "crictl"
    description: "CLI for kubelet CRI"
    pipeline:
      - runs: |
          install -Dm755 ${{targets.destdir}}/usr/bin/crictl ${{targets.subpkgdir}}/usr/bin/crictl

  - name: "critest"
    description: "validation test suites for kubelet CRI"
    pipeline:
      - runs: |
          install -Dm755 ${{targets.destdir}}/usr/bin/critest ${{targets.subpkgdir}}/usr/bin/critest

update:
  enabled: true
  github:
    identifier: kubernetes-sigs/cri-tools
    strip-prefix: v
