package:
  name: dagger
  version: 0.12.4
  epoch: 1
  description: Application Delivery as Code that Runs Anywhere
  copyright:
    - license: Apache-2.0

environment:
  environment:
    CGO_ENABLED: 0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/dagger/dagger
      tag: v${{package.version}}
      expected-commit: c0d2d86f30df377f3245b828b84112b3e849c355

  - uses: go/bump
    with:
      deps: google.golang.org/grpc@v1.64.1 github.com/docker/docker@v27.1.1

  - uses: go/build
    with:
      ldflags: -s -w  -X github.com/dagger/dagger/engine.Version=v${{package.version}}
      output: dagger
      packages: ./cmd/dagger

  - uses: strip

update:
  enabled: true
  ignore-regex-patterns:
    - 'sdk'
    - 'helm'
  github:
    identifier: dagger/dagger
    strip-prefix: v
    use-tag: true

test:
  pipeline:
    - runs: |
        dagger version
