package:
  name: dive
  version: 0.12.0
  epoch: 11
  description: A tool for exploring each layer in a docker image
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/wagoodman/dive
      tag: v${{package.version}}
      expected-commit: 925cdd86482edec42185794620a1e616b79bbee5

  - uses: go/bump
    with:
      deps: golang.org/x/net@v0.23.0 github.com/docker/cli@v20.10.9 github.com/docker/docker@v26.1.5
      replaces: google.golang.org/genproto=google.golang.org/genproto@v0.0.0-20240730163845-b1a4ccb954bf

  - uses: go/build
    with:
      packages: .
      output: dive
      ldflags: -X main.version=v${{package.version}} -X main.commit=$(git rev-parse HEAD) -X main.buildTime=$(date +%F-%T)

  - uses: strip

update:
  enabled: true
  github:
    identifier: wagoodman/dive
    strip-prefix: v
