package:
  name: dua
  version: 2.29.2
  epoch: 0
  description: "View disk space usage and delete unwanted data, fast."
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - rust
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/Byron/dua-cli
      expected-commit: 60ed763e98620664c06eac5fd7972f407ae97503
      tag: v${{package.version}}

  - name: Configure and build
    runs: |
      cargo build --release --no-default-features --features tui-crossplatform
      mkdir -p ${{targets.destdir}}/usr/bin/
      mv target/release/dua ${{targets.destdir}}/usr/bin/dua

  - uses: strip

update:
  enabled: true
  github:
    identifier: Byron/dua-cli
    strip-prefix: v

test:
  pipeline:
    - runs: |
        dua -V
