package:
  name: ethtool
  version: "6.10"
  epoch: 0
  description: Utility for controlling network drivers and hardware
  copyright:
    - license: GPL-2.0-only

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - libmnl-dev
      - linux-headers

pipeline:
  - uses: fetch
    with:
      expected-sha256: cc613fe8a2bcddee17a1e6e0d763c0f3ea33c7e930658d2d7f601aa65e426a1f
      uri: https://www.kernel.org/pub/software/network/ethtool/ethtool-${{package.version}}.tar.xz

  - uses: autoconf/configure
    with:
      opts: |
        --build=$CBUILD \
        --host=$CHOST \
        --prefix=/usr \
        --mandir=/usr/share/man

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: "ethtool-doc"
    description: "ethtool manpages"
    pipeline:
      - uses: split/manpages

update:
  enabled: true
  release-monitor:
    identifier: 763
