package:
  name: flux
  version: 2.3.0
  epoch: 6
  description: Open and extensible continuous delivery solution for Kubernetes. Powered by GitOps Toolkit.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - curl
      - git
      - go
      - kustomize

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 896e0fa46d5107a05e953dd0a5261d78a145ec8c
      repository: https://github.com/fluxcd/flux2
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: github.com/Azure/azure-sdk-for-go/sdk/azidentity@v1.6.0 github.com/hashicorp/go-retryablehttp@v0.7.7 github.com/docker/docker@v26.1.5

  - runs: |
      mkdir -p "${{targets.destdir}}"/usr/bin
      VERSION=${{package.version}} make build
      install -Dm755 bin/flux ${{targets.destdir}}/usr/bin/flux

  - runs: |
      ${{targets.destdir}}/usr/bin/flux version --client| grep "flux: v${{package.version}}"

  - uses: strip

subpackages:
  - name: "flux-compat"
    description: "Compatibility package to place binaries in the location expected by upstream helm charts"
    pipeline:
      - runs: |
          # The helm chart expects the flux binaries to be in /usr/local/bin instead of /usr/bin
          mkdir -p "${{targets.subpkgdir}}"/usr/local/bin
          ln -sf /usr/bin/flux ${{targets.subpkgdir}}/usr/local/bin/flux

update:
  enabled: true
  github:
    identifier: fluxcd/flux2
    strip-prefix: v
