package:
  name: gh
  version: 2.54.0
  epoch: 1
  description: GitHub's official command line tool
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 89cbcfe7eb186ff4edbe10792d17bdc55b04f297
      repository: https://github.com/cli/cli
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: github.com/docker/docker@v26.1.5

  - runs: make install prefix=${{targets.destdir}}/usr

  - uses: strip

update:
  enabled: true
  github:
    identifier: cli/cli
    strip-prefix: v

test:
  pipeline:
    - runs: |
        gh --version
