# Source is on gitlab so we can't use github for updates
#nolint:git-checkout-must-use-github-updates
package:
  name: gitlab-pages-17.2
  version: 17.2.2
  epoch: 0
  description: GitLab Pages daemon used to serve static websites for GitLab users.
  copyright:
    - license: MIT
  dependencies:
    provides:
      - gitlab-pages=${{package.full-version}}

var-transforms:
  - from: ${{package.version}}
    match: ^(\d+\.\d+)\.\d+$
    replace: "$1"
    to: major-minor-version

pipeline:
  - uses: git-checkout
    with:
      repository: https://gitlab.com/gitlab-org/gitlab-pages.git
      tag: v${{package.version}}
      expected-commit: eeda128d39c695e2dc34da037afe873d74d21eb7

  - uses: go/build
    with:
      packages: .
      output: gitlab-pages
      tags: continuous_profiler_stackdriver
      ldflags: "-w -X main.VERSION=${{package.version}} -X main.REVISION=${{package.version}}"

  - runs: |
      mkdir -p ${{targets.contextdir}}/srv/gitlab-pages
      mkdir -p ${{targets.contextdir}}/var/log/gitlab

subpackages:
  - name: gitlab-pages-compat-${{vars.major-minor-version}}
    description: Links GitLab pages to bin directory
    dependencies:
      provides:
        - gitlab-pages-compat=${{package.full-version}}
    pipeline:
      - runs: |
          mkdir -p ${{targets.contextdir}}/bin
          ln -sf /usr/bin/gitlab-pages ${{targets.contextdir}}/bin/gitlab-pages

update:
  enabled: true
  github:
    identifier: gitlabhq/gitlabhq
    strip-prefix: v
    use-tag: true
    tag-filter: v17.2
