package:
  name: gst-plugins-bad
  version: 1.24.6
  epoch: 0
  description: GStreamer streaming media framework bad plug-ins
  copyright:
    - license: GPL-2.0-or-later AND LGPL-2.0-or-later

environment:
  contents:
    packages:
      - alsa-lib-dev
      - build-base
      - busybox
      - ca-certificates-bundle
      - cdparanoia-dev
      - cmake
      - expat-dev
      - gdk-pixbuf
      - glib-dev
      - glib-gir
      - gobject-introspection-dev
      - graphene-dev
      - gst-plugins-base-dev
      - gstreamer
      - gstreamer-dev
      - gtk-3-dev
      - libdrm-dev
      - libice-dev
      - libogg-dev
      - libsm-dev
      - libtheora-dev
      - libvorbis-dev
      - libxv-dev
      - mesa-dev
      - mesa-gbm
      - mesa-gl
      - mesa-glapi
      - mesa-gles
      - meson
      - opus-dev
      - orc-compiler
      - orc-dev
      - perl

pipeline:
  - uses: fetch
    with:
      expected-sha256: 8f4d965513e7827c1f547c1e749e4ef2812b371974fe64857fe5029a19c5b64c
      uri: https://gstreamer.freedesktop.org/src/gst-plugins-bad/gst-plugins-bad-${{package.version}}.tar.xz

  - uses: meson/configure
    with:
      opts: |
        -Db_lto=true \
        -Dpackage-origin="https://github.com/wolfi-dev" \
        -Dpackage-name="GStreamer bad plug-ins (Wolfi-Linux)" \
        -Dintrospection=enabled \
        -Dsctp=enabled \

  - uses: meson/compile

  - uses: meson/install

  - uses: strip

subpackages:
  - name: ${{package.name}}-dev
    dependencies:
      runtime:
        - ${{package.name}}
    pipeline:
      - uses: split/dev
    description: ${{package.name}} dev

  - name: ${{package.name}}-doc
    pipeline:
      - uses: split/manpages
    description: ${{package.name}} manpages

update:
  enabled: true
  release-monitor:
    identifier: 21849
