package:
  name: guac
  version: 0.8.0
  epoch: 3
  description: GUAC aggregates software security metadata into a high fidelity graph database.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/guacsec/guac
      tag: v${{package.version}}
      expected-commit: 0c6dc86ff3ab98e9572d5c936160c75e84d7c4df

  - uses: go/bump
    with:
      deps: github.com/regclient/regclient@v0.7.1 github.com/docker/docker@v26.1.5

  - uses: go/build
    with:
      packages: ./cmd/guaccollect
      output: guaccollect
      ldflags: -X github.com/guacsec/guac/pkg/version.Version=${{package.version}}

  - uses: strip

subpackages:
  - name: guacingest
    pipeline:
      - uses: go/build
        with:
          ldflags: -X github.com/guacsec/guac/pkg/version.Version=${{package.version}}
          packages: ./cmd/guacingest
          output: guacingest
      - uses: strip

  - name: guacone
    pipeline:
      - uses: go/build
        with:
          ldflags: -X github.com/guacsec/guac/pkg/version.Version=${{package.version}}
          packages: ./cmd/guacone
          output: guacone
      - uses: strip

  - name: guacgql
    pipeline:
      - uses: go/build
        with:
          ldflags: -X github.com/guacsec/guac/pkg/version.Version=${{package.version}}
          packages: ./cmd/guacgql
          output: guacgql
      - uses: strip

  - name: guaccsub
    pipeline:
      - uses: go/build
        with:
          ldflags: -X github.com/guacsec/guac/pkg/version.Version=${{package.version}}
          packages: ./cmd/guaccsub
          output: guaccsub
      - uses: strip

update:
  enabled: true
  github:
    identifier: guacsec/guac
    strip-prefix: v
    use-tag: true
    tag-filter: v
