package:
  name: hugo-extended
  version: 0.132.0
  epoch: 0
  description: The world's fastest framework for building websites.
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - libstdc++

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - git

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/gohugoio/hugo
      tag: v${{package.version}}
      expected-commit: 005e895a386e59dd38418066b3280fd98a33c96b

  - uses: go/build
    with:
      packages: .
      output: hugo
      tags: extended

  - uses: strip

update:
  enabled: true
  github:
    identifier: gohugoio/hugo
    strip-prefix: v
