package:
  name: ko
  version: 0.16.0
  epoch: 1
  description: Simple, fast container image builder for Go applications.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      destination: ko
      expected-commit: 0dcace336cc5f723150d77487dbaf56f849cc361
      repository: https://github.com/ko-build/ko
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: github.com/docker/docker@v26.1.5
      modroot: ko

  - uses: go/build
    with:
      ldflags: -X github.com/google/ko/pkg/commands.Version=${{package.version}}
      modroot: ko
      output: ko
      packages: .
      vendor: true

  - uses: strip

update:
  enabled: true
  github:
    identifier: ko-build/ko
    strip-prefix: v
