package:
  name: kyverno-1.12
  version: 1.12.5
  epoch: 2
  description: Kubernetes Native Policy Management
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle
    provides:
      - kyverno=${{package.full-version}}

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - go
      - wolfi-baselayout

pipeline:
  - uses: git-checkout
    with:
      expected-commit: b7fb616a6db3081a7c6d1d72d375819e777064ee
      repository: https://github.com/kyverno/kyverno
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: golang.org/x/net@v0.23.0 github.com/Azure/azure-sdk-for-go/sdk/azidentity@v1.6.0 github.com/hashicorp/go-retryablehttp@v0.7.7 github.com/docker/docker@v26.1.5

  - runs: |
      make build-all
      mkdir -p ${{targets.destdir}}/usr/bin
      install -Dm755 cmd/kyverno/kyverno ${{targets.destdir}}/usr/bin/kyverno

  - uses: strip

subpackages:
  - name: kyverno-init-container-1.12
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin
          install -Dm755 cmd/kyverno-init/kyvernopre ${{targets.subpkgdir}}/usr/bin/kyvernopre
    dependencies:
      provides:
        - kyverno-init-container=${{package.full-version}}

  - name: kyverno-reports-controller-1.12
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin
          install -Dm755 cmd/reports-controller/reports-controller ${{targets.subpkgdir}}/usr/bin/reports-controller
    dependencies:
      provides:
        - kyverno-reports-controller=${{package.full-version}}

  - name: kyverno-background-controller-1.12
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin
          install -Dm755 cmd/background-controller/background-controller ${{targets.subpkgdir}}/usr/bin/background-controller
    dependencies:
      provides:
        - kyverno-background-controller=${{package.full-version}}

  - name: kyverno-cleanup-controller-1.12
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin
          install -Dm755 cmd/cleanup-controller/cleanup-controller ${{targets.subpkgdir}}/usr/bin/cleanup-controller
    dependencies:
      provides:
        - kyverno-cleanup-controller=${{package.full-version}}

  - name: kyverno-cli-1.12
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin
          install -Dm755 cmd/cli/kubectl-kyverno/kubectl-kyverno ${{targets.subpkgdir}}/usr/bin/kubectl-kyverno
    dependencies:
      provides:
        - kyverno-cli=${{package.full-version}}

update:
  enabled: true
  ignore-regex-patterns:
    - "-beta"
    - "-rc"
  github:
    identifier: kyverno/kyverno
    strip-prefix: v
    tag-filter: v1.12.

test:
  pipeline:
    - runs: kyverno --help
