package:
  name: libsass
  version: "3.6.6"
  epoch: 0
  description: C/C++ implementation of a Sass compiler
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - libtool
      - wolfi-baselayout

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/sass/libsass
      tag: ${{package.version}}
      expected-commit: 7037f03fabeb2b18b5efa84403f5a6d7a990f460

  - runs: autoreconf -vfi

  - uses: autoconf/configure
    with:
      opts: |
        --disable-static

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: ${{package.name}}-dev
    description: C/C++ implementation of a Sass compiler - development files
    dependencies:
      runtime:
        - libsass
    pipeline:
      - uses: split/dev

update:
  enabled: true
  github:
    identifier: sass/libsass
