package:
  name: libssh
  version: 0.11.0
  epoch: 0
  description: Library for accessing ssh client services through C libraries
  copyright:
    - license: LGPL-2.1-or-later AND BSD-2-Clause

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - openssl-dev
      - samurai
      - xz
      - zlib-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://git.libssh.org/projects/libssh.git
      tag: libssh-${{package.version}}
      expected-commit: 894e07aede659d26e13569ac9987191b81bc359d

  - runs: |
      cmake -B build -G Ninja \
        -DCMAKE_BUILD_TYPE=None \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_INSTALL_LIBDIR=lib \
        -DWITH_GSSAPI=OFF \
        -DUNIT_TESTING=OFF
      cmake --build build
      DESTDIR="${{targets.destdir}}" cmake --install build

  - uses: strip

subpackages:
  - name: "libssh-dev"
    description: "headers for libssh"
    pipeline:
      - uses: split/dev

update:
  enabled: true
  release-monitor:
    identifier: 1729
