package:
  name: libsdl2
  version: 2.30.6
  epoch: 0
  description: Simple DirectMedia Layer is a cross-platform development library designed to provide low level access to audio, keyboard, mouse, joystick, and graphics hardware via OpenGL and Direct3D.
  copyright:
    - license: Zlib

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/libsdl-org/SDL
      tag: release-${{package.version}}
      expected-commit: ba2f78a0069118a6c583f1fbf1420144ffa35bad

  - uses: cmake/configure

  - uses: cmake/build

  - uses: cmake/install

subpackages:
  - name: ${{package.name}}-dev
    dependencies:
      runtime:
        - libsdl2
    pipeline:
      - uses: split/dev

  - name: ${{package.name}}-doc
    pipeline:
      - uses: split/dev

update:
  enabled: true
  github:
    identifier: libsdl-org/SDL
    strip-prefix: release-

test:
  environment:
    contents:
      packages:
        - ${{package.name}}-dev
        - pkgconf
  pipeline:
    - runs: |
        set -euo pipefail
        pkg-config --modversion sdl2 | grep -q "${{package.version}}"
