package:
  name: libvips
  version: 8.15.3
  epoch: 0
  description: "A fast image processing library with low memory needs"
  copyright:
    - license: LGPL-2.1-or-later

environment:
  contents:
    packages:
      - bubblewrap
      - build-base
      - busybox
      - cmake
      - expat-dev
      - glib-dev
      - libexif-dev
      - libjpeg-turbo-dev
      - librsvg-dev
      - meson

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/libvips/libvips
      expected-commit: 1a86d4e153536e035d1907652391a26f77cbe1b8
      tag: v${{package.version}}

  - uses: meson/configure

  - uses: meson/compile

  - uses: meson/install

  - uses: strip

subpackages:
  - name: libvips-dev
    pipeline:
      - uses: split/dev

  - name: libvips-doc
    pipeline:
      - uses: split/manpages

update:
  enabled: true
  ignore-regex-patterns:
    - ".*-beta"
    - ".*-rc\\d+$"
  github:
    identifier: libvips/libvips
    strip-prefix: v
