package:
  name: lksctp-tools
  version: 1.0.20
  epoch: 0
  description: "The Linux SCTP helper library"
  copyright:
    - license: GPL-2.0-only AND LGPL-2.1-only

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - libtool
      - linux-headers
      - m4

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/sctp/lksctp-tools
      tag: v${{package.version}}
      expected-commit: f6d64dc3fdcba8f7ced61ea26270ebc0c38b5312

  - runs: |
      libtoolize --force --copy
      aclocal
      autoheader
      automake --foreign --add-missing --copy
      autoconf

  - uses: autoconf/configure
    with:
      opts: |
        --enable-shared \
        --enable-static

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: libsctp-dev
    pipeline:
      - uses: split/dev
    description: libsctp dev

  - name: libsctp-doc
    pipeline:
      - uses: split/manpages
      - uses: split/infodir

  - name: libsctp
    description: libsctp library
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib
          mv "${{targets.destdir}}"/usr/lib/libsctp.so.* "${{targets.subpkgdir}}"/usr/lib/

update:
  enabled: true
  github:
    use-tag: true
    identifier: sctp/lksctp-tools
    strip-prefix: lksctp-tools-
