package:
  name: lua-resty-cache
  version: "0.14"
  epoch: 0
  description: "lua-resty-lrucache - Lua-land LRU cache based on the LuaJIT FFI."
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - bash
      - build-base
      - ca-certificates-bundle
      - wolfi-base
  environment:
    PREFIX: /usr

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/openresty/lua-resty-lrucache
      tag: v${{package.version}}
      expected-commit: 1293147608c9dfb0ee163e39a4c8997476e8f741

  - uses: autoconf/make-install

update:
  enabled: true
  github:
    identifier: openresty/lua-resty-lrucache
    strip-prefix: v
    use-tag: true
