package:
  name: mailpit
  version: 1.20.1
  epoch: 0
  description: An email and SMTP testing tool with API for developers
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go
      - nodejs-20
      - npm

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/axllent/mailpit
      tag: v${{package.version}}
      expected-commit: 37ea30fcdb6d630b8092745d8307e71a5e71e46d

  - runs: |
      npm install
      npm run package

  - runs: |
      CGO_ENABLED=0 go build -ldflags "-s -w -X github.com/axllent/mailpit/config.Version=${{package.version}}" -o mailpit
      mkdir -p ${{targets.destdir}}/usr/bin
      mv mailpit ${{targets.destdir}}/usr/bin/

  - uses: strip

test:
  pipeline:
    - name: Verify mailpit binary
      runs: |
        mailpit version || exit 1

update:
  enabled: true
  github:
    identifier: axllent/mailpit
    tag-filter: v
    strip-prefix: v
