package:
  name: nerdctl
  version: 1.7.6
  epoch: 8
  description: Docker-compatible CLI for containerd, with support for Compose, Rootless, eStargz, OCIcrypt, IPFS, ...
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/containerd/nerdctl
      tag: v${{package.version}}
      expected-commit: 845e989f69d25b420ae325fedc8e70186243fd93

  - uses: go/bump
    with:
      deps: github.com/docker/cli@v26.1.4 github.com/docker/docker@v26.1.5

  - runs: |
      make nerdctl
      install -Dm755 ./_output/nerdctl ${{targets.destdir}}/usr/bin/nerdctl

  - uses: strip

update:
  enabled: true
  github:
    identifier: containerd/nerdctl
    strip-prefix: v
