package:
  name: pulumi-language-dotnet
  version: 3.66.1
  epoch: 0
  description: Pulumi Language SDK for Dotnet
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - git
      - go

pipeline:
  - uses: git-checkout
    with:
      expected-commit: f359112840bced9a8f5a77c2013c2990dc734c9b
      repository: https://github.com/pulumi/pulumi-dotnet.git
      tag: v${{package.version}}

  - uses: go/build
    with:
      ldflags: -s -w -X github.com/pulumi/pulumi-language-dotnet/pkg/version.Version=v${{package.version}}
      modroot: pulumi-language-dotnet
      output: pulumi-language-dotnet
      packages: .

  - uses: strip

update:
  enabled: true
  github:
    identifier: pulumi/pulumi-dotnet
    strip-prefix: v
