package:
  name: py3-pgcli
  version: 4.1.0
  epoch: 0
  description: CLI for Postgres Database. With auto-completion and syntax highlighting.
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - py3-cli-helpers
      - py3-click
      - py3-configobj
      - py3-pendulum
      - py3-pgspecial
      - py3-prompt-toolkit
      - py3-psycopg
      - py3-pygments
      - py3-setproctitle
      - py3-sqlparse
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-setuptools
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/dbcli/pgcli
      tag: v${{package.version}}
      expected-commit: 46fe654cd16a3af837639dc2c8be60d1b7a038c7

  - name: Python Build
    runs: python setup.py build

  - name: Python Install
    runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  github:
    identifier: dbcli/pgcli
    strip-prefix: v
    use-tag: true

test:
  pipeline:
    - uses: python/import
      with:
        import: pgcli
