package:
  name: py3-retrying
  version: 1.3.4
  epoch: 4
  description: "python 2 and 3 compatibility library"
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - py3-six
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-setuptools
      - py3-six
      - python3
      - wolfi-base

pipeline:
  - uses: fetch
    with:
      uri: https://files.pythonhosted.org/packages/source/r/retrying/retrying-${{package.version}}.tar.gz
      expected-sha256: 345da8c5765bd982b1d1915deb9102fd3d1f7ad16bd84a9700b85f64d24e8f3e

  - runs: |
      python3 setup.py build

  - runs: |
      python3 setup.py install --prefix=/usr --root="${{targets.destdir}}" --skip-build

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 13217

test:
  pipeline:
    - uses: python/import
      with:
        import: retrying
