package:
  name: py3-kiwisolver
  version: 1.4.5
  epoch: 3
  description: A fast implementation of the Cassowary constraint solver
  copyright:
    - license: BSD-3-Clause-Attribution
  dependencies:
    runtime:
      - py3-typing-extensions
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-build
      - py3-cppy
      - py3-installer
      - py3-pip
      - py3-setuptools
      - py3-setuptools-scm
      - python3
      - python3-dev
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/nucleic/kiwi
      expected-commit: 03adafeb0f1188e34cde4c7ca8fe384912bd9e1b
      tag: ${{package.version}}

  - runs: |
      git fetch --prune --unshallow
      git fetch --depth=1 origin +refs/tags/*:refs/tags/*

  - name: Python Build
    runs: |
      python -m build

  - name: Python Install
    runs: python3 -m installer -d "${{targets.destdir}}" dist/*.whl

  - uses: strip

update:
  enabled: true
  github:
    identifier: nucleic/kiwi

test:
  pipeline:
    - uses: python/import
      with:
        import: kiwisolver
