package:
  name: py3-rsa
  version: 4.9
  epoch: 4
  description: "Pure-Python3 RSA implementation"
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - py3-asn1
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-setuptools
      - python3
      - wolfi-base

pipeline:
  - uses: fetch
    with:
      uri: https://files.pythonhosted.org/packages/source/r/rsa/rsa-${{package.version}}.tar.gz
      expected-sha256: e38464a49c6c85d7f1351b0126661487a7e0a14a50f1675ec50eb34d4f20ef21

  - runs: |
      python3 setup.py build

  - runs: |
      python3 setup.py install --prefix=/usr --root="${{targets.destdir}}" --skip-build

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 12011

test:
  pipeline:
    - uses: python/import
      with:
        import: rsa
