package:
  name: py3-pkgconfig
  version: 1.5.5
  epoch: 3
  description: Interface Python with pkg-config
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - python-3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-setuptools
      - python-3
      - wolfi-base

pipeline:
  - uses: fetch
    with:
      expected-sha256: deb4163ef11f75b520d822d9505c1f462761b4309b1bb713d08689759ea8b899
      uri: https://files.pythonhosted.org/packages/source/p/pkgconfig/pkgconfig-${{package.version}}.tar.gz

  - name: Python Build
    uses: python/build

  - name: Python Install
    uses: python/install

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 209128

test:
  pipeline:
    - uses: python/import
      with:
        import: pkgconfig
