package:
  name: py3-mdurl
  version: 0.1.2
  epoch: 2
  description: "Markdown URL utilities"
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - py3-flit-core
      - py3-gpep517
      - py3-setuptools
      - py3-wheel
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/executablebooks/mdurl
      tag: ${{package.version}}
      expected-commit: 596bf1c8752de45fa576a52c315d6d8cc5bb1a4e

  - runs: |
      python3 -m gpep517 build-wheel \
        --wheel-dir dist \
        --output-fd 3 3>&1 >&2
      python3 -m installer \
        -d "${{targets.destdir}}" \
        dist/mdurl-${{package.version}}-*.whl
      install -Dm644 LICENSE \
        "${{targets.destdir}}"/usr/share/licenses/${{package.name}}/LICENSE

  - uses: strip

update:
  enabled: true
  github:
    identifier: executablebooks/mdurl

test:
  pipeline:
    - uses: python/import
      with:
        import: mdurl
