package:
  name: py3-invoke
  version: 2.2.0
  epoch: 1
  description: Pythonic task management & command execution.
  copyright:
    - license: BSD-2-Clause
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-setuptools
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/pyinvoke/invoke
      expected-commit: 07b836f2663bb073a7bcef3d6c454e1dc6b867ae
      tag: ${{package.version}}

  - name: Python Build
    runs: python setup.py build

  - name: Python Install
    runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  ignore-regex-patterns:
    - ^[a-zA-Z]
  enabled: true
  github:
    identifier: pyinvoke/invoke
    use-tag: true

test:
  pipeline:
    - uses: python/import
      with:
        import: invoke
