package:
  name: py3-ipaddress
  version: 1.0.23
  epoch: 2
  description: IPv4/IPv6 manipulation library
  copyright:
    - license: PSF-2.0
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-setuptools
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/phihag/ipaddress
      tag: v${{package.version}}
      expected-commit: d8aef06cc3ca8a6fd8570cda665b2bb879a29390

  - name: Python Build
    runs: python setup.py build

  - name: Python Install
    runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  github:
    identifier: phihag/ipaddress
    strip-prefix: v
    use-tag: true

test:
  pipeline:
    - uses: python/import
      with:
        import: ipaddress
