package:
  name: py3-oauthlib
  version: 3.2.2
  epoch: 3
  description: A generic, spec-compliant, thorough implementation of the OAuth request-signing logic
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-setuptools
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/oauthlib/oauthlib
      tag: v${{package.version}}
      expected-commit: e6c33e41a8ce6dadff387cdc4613a55b63d1827e

  - name: Python Build
    runs: python setup.py build

  - name: Python Install
    runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  github:
    identifier: oauthlib/oauthlib
    strip-prefix: v

test:
  pipeline:
    - uses: python/import
      with:
        import: oauthlib
