package:
  name: py3-ply
  version: 3.11_git20180215
  epoch: 3
  description: Python Lex & Yacc
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - python3

var-transforms:
  - from: ${{package.version}}
    match: _git(.*)
    replace: ""
    to: mangled-package-version

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-setuptools
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/dabeaz/ply
      tag: ${{vars.mangled-package-version}}
      expected-commit: 0f398b72618c1564d71f7dc0558e6722b241875a

  - name: Python Build
    runs: python setup.py build

  - name: Python Install
    runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: false
  exclude-reason: some sort of a deprecated project

test:
  pipeline:
    - uses: python/import
      with:
        import: ply
