package:
  name: py3-pycurl
  version: 7.45.3
  epoch: 0
  description: PycURL -- A Python Interface To The cURL library
  copyright:
    - license: LGPL-2.1-or-later AND MIT
  dependencies:
    runtime:
      - python-3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - curl-dev
      - openssl-dev
      - py3-setuptools
      - python-3
      - python-3-dev
      - wolfi-base

# transform melange version from REL_7_45_2 to 7.45.2
var-transforms:
  - from: ${{package.version}}
    match: \.
    replace: _
    to: mangled-package-version

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 64bcc052698407ff82451d73317cf69b944a100e
      repository: https://github.com/pycurl/pycurl
      tag: REL_${{vars.mangled-package-version}}

  - name: Python Build
    uses: python/build-wheel

  - uses: strip

update:
  enabled: true
  version-separator: _
  github:
    identifier: pycurl/pycurl
    strip-prefix: REL_
    tag-filter: REL_
    use-tag: true

test:
  pipeline:
    - uses: python/import
      with:
        import: pycurl
