package:
  name: py3-oscrypto
  version: 1.3.0
  epoch: 0
  description: Compiler-free Python crypto library backed by the OS, supporting CPython and PyPy
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-setuptools
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/wbond/oscrypto
      expected-commit: c91c8642e712e7801bf40403dd72165b607f4930
      tag: ${{package.version}}

  - name: Python Build
    runs: python setup.py build

  - name: Python Install
    runs: python setup.py install --prefix=/usr --root="${{targets.destdir}}"

  - uses: strip

update:
  enabled: true
  github:
    identifier: wbond/oscrypto
    use-tag: true

test:
  pipeline:
    - uses: python/import
      with:
        import: oscrypto
