package:
  name: py3-nltk
  version: 3.8.1
  epoch: 1
  description: Natural Language Toolkit
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - numpy
      - py3-click
      - py3-joblib
      - py3-matplotlib
      - py3-mdit-plain
      - py3-mdit-py-plugins
      - py3-parsing
      - py3-regex
      - py3-scikit-learn
      - py3-scipy
      - py3-tqdm
      - py3-twython
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-click
      - py3-joblib
      - py3-regex
      - py3-setuptools
      - py3-tqdm
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/nltk/nltk
      expected-commit: 63a63b1a7793aceceb1efc23bc1fd87e7095f9d5
      tag: ${{package.version}}

  - name: Python Build
    uses: python/build

  - name: Python Install
    uses: python/install

  - uses: strip

update:
  enabled: true
  github:
    identifier: nltk/nltk
    use-tag: true

test:
  pipeline:
    - uses: python/import
      with:
        import: nltk
