package:
  name: ruby3.2-activesupport
  version: 7.2.0
  epoch: 0
  description: A toolkit of support libraries and Ruby core extensions extracted from the Rails framework. Rich support for multibyte strings, internationalization, time zones, and testing.
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - ruby3.2-concurrent-ruby
      - ruby3.2-i18n
      - ruby3.2-tzinfo

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ruby-3.2
      - ruby-3.2-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/rails/rails
      tag: v${{package.version}}
      expected-commit: fb6c4305939da06efdf2893d99130e7829c53e8b

  - uses: ruby/build
    with:
      gem: ${{vars.gem}}
      dir: activesupport

  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}
      dir: activesupport

  - uses: ruby/clean

vars:
  gem: activesupport

update:
  enabled: true
  github:
    identifier: rails/rails
    strip-prefix: v
