package:
  name: tekton-chains
  version: 0.21.1
  epoch: 5
  description: Supply Chain Security in Tekton Pipelines
  copyright:
    - license: Apache-2.0

environment:
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 4cb5c506d26de677f54516e1bf2a4a55d9739e64
      repository: https://github.com/tektoncd/chains
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: github.com/Azure/azure-sdk-for-go/sdk/azidentity@v1.6.0 github.com/hashicorp/go-retryablehttp@v0.7.7 github.com/docker/docker@v26.1.5

  - uses: go/build
    with:
      output: tekton-chains
      packages: ./cmd/controller

update:
  enabled: true
  github:
    identifier: tektoncd/chains
    strip-prefix: v
