package:
  name: tekton-pipelines
  version: 0.62.1
  epoch: 1
  description: A cloud-native Pipeline resource.
  copyright:
    - license: Apache-2.0

environment:
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/tektoncd/pipeline
      tag: v${{package.version}}
      expected-commit: e58ca130a3c7ccb7fff1362d9093f7da95558f75
      destination: tekton

  - uses: go/bump
    with:
      deps: github.com/Azure/azure-sdk-for-go/sdk/azidentity@v1.6.0 github.com/hashicorp/go-retryablehttp@v0.7.7 google.golang.org/grpc@v1.64.1 github.com/docker/docker@v26.1.5
      modroot: tekton

  - uses: go/build
    with:
      packages: ./cmd/controller
      output: tekton-pipelines-controller
      modroot: tekton
      vendor: true

data:
  - name: cmds
    items:
      entrypoint: entrypoint
      events: events
      nop: nop
      resolvers: resolvers
      sidecarlogresults: sidecarlogresults
      webhook: webhook
      workingdirinit: workingdirinit

subpackages:
  - range: cmds
    name: tekton-pipelines-${{range.key}}
    description: tekton pipelines ${{range.key}}
    pipeline:
      - uses: go/build
        with:
          packages: ./cmd/${{range.key}}
          output: tekton-pipelines-${{range.key}}
          modroot: tekton

update:
  enabled: true
  github:
    identifier: tektoncd/pipeline
    strip-prefix: v
