package:
  name: teleport
  version: 16.1.4
  epoch: 1
  description: The easiest, and most secure way to access and protect all of your infrastructure.
  copyright:
    - license: AGPL-3.0-only
  dependencies:
    runtime:
      - posix-libc-utils # getent

environment:
  contents:
    packages:
      - autoconf
      - automake
      - binaryen
      - build-base
      - busybox
      - ca-certificates-bundle
      - corepack
      - go
      - node-gyp
      - nodejs
      - openssl-dev
      - pnpm
      - python3
      - rustup
      - wasm-pack
      - yarn
      - zstd-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/gravitational/teleport
      expected-commit: acdd343922cabefa026312a84e88d9999f09028b
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: github.com/docker/docker@v26.1.5

  - runs: |
      # https://github.com/gravitational/teleport#building-teleport
      mkdir -p "${{targets.contextdir}}"/var/lib/teleport
      mkdir -p "${{targets.contextdir}}"/usr/local/bin

      # This build requires the stable version of rust, managed by rustup, because it requires a few other toolchains too.
      rustup install stable
      rustup target add wasm32-unknown-unknown

      # This is a bit of a hack, but it's the easiest way to get the right version of rustc and cargo in the path.
      export PATH="$HOME/.rustup/toolchains/stable-${{host.triplet.rust}}/bin:$PATH"
      make full

      # create me a for loop that iterates over the binaries in build/
      # and installs them to "${{targets.contextdir}}"/usr/local/bin
      for bin in build/*; do
        echo "Installing $bin to /usr/local/bin"
        install -Dm755 $bin -t "${{targets.contextdir}}"/usr/local/bin
      done

  - uses: strip

update:
  enabled: true
  github:
    identifier: gravitational/teleport
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - wait-for-it
  pipeline:
    - runs: |
        teleport configure -o file
        teleport start -c /etc/teleport.yaml &

        # wait for teleport to start :3080
        wait-for-it localhost:3080 -t 10

        echo "Teleport is running on port 3080!"

        # create a user
        tctl get roles --format=text
