package:
  name: timestamp-authority
  version: 1.2.0
  epoch: 0
  description: Software supply chain timestamp authority
  target-architecture:
    - all
  copyright:
    - license: Apache-2.0
      paths:
        - "*"
  checks:
    disabled:
      - empty

environment:
  contents:
    packages:
      - busybox
      - git

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/sigstore/timestamp-authority
      tag: v${{package.version}}
      expected-commit: c21da35174dd1a44ff425f695f87e99061c52d99

subpackages:
  - name: ${{package.name}}-server
    pipeline:
      - uses: go/build
        with:
          modroot: .
          subpackage: "true"
          packages: ./cmd/timestamp-server
          output: timestamp-server
          ldflags: -w
      - uses: strip

  - name: ${{package.name}}-cli
    pipeline:
      - uses: go/build
        with:
          modroot: .
          subpackage: "true"
          packages: ./cmd/timestamp-cli
          output: timestamp-cli
          ldflags: -w
      - uses: strip


update:
  enabled: true
  github:
    identifier: sigstore/timestamp-authority
    strip-prefix: v
