package:
  name: tkn
  version: 0.37.0
  epoch: 6
  description: A CLI for interacting with Tekton!
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/tektoncd/cli
      tag: v${{package.version}}
      expected-commit: f8b6dc07a0f51f93a138c287ccdc81fbef410554

  - uses: go/bump
    with:
      deps: github.com/Azure/azure-sdk-for-go/sdk/azidentity@v1.6.0 github.com/hashicorp/go-retryablehttp@v0.7.7 github.com/docker/docker@v26.1.5

  - runs: |
      make bin/tkn
      install -Dm755 ./bin/tkn ${{targets.destdir}}/usr/bin/tkn

  - uses: strip

update:
  enabled: true
  github:
    identifier: tektoncd/cli
    strip-prefix: v
