package:
  name: up
  version: 0.32.1
  epoch: 1
  description: The Upbound CLI
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - bash
      - build-base
      - busybox
      - go
  environment:
    CGO_ENABLED: 0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/upbound/up
      tag: v${{package.version}}
      expected-commit: b941b579f31f5a826f944ba099941c78b2d88e05

  - uses: go/bump
    with:
      deps: oras.land/oras-go@v1.2.5 helm.sh/helm/v3@v3.14.2 google.golang.org/protobuf@v1.33.0 golang.org/x/net@v0.23.0 github.com/Azure/azure-sdk-for-go/sdk/azidentity@v1.6.0 github.com/docker/docker@v26.1.5
      replaces: github.com/docker/cli=github.com/docker/cli@v25.0.5+incompatible github.com/docker/docker=github.com/docker/docker@v26.1.5+incompatible oras.land/oras-go=oras.land/oras-go@v1.2.5
      show-diff: true

  - runs: |
      make submodules
      make install

      # This installs `up` into `$GOPATH/bin/up`, but we want it in `/usr/bin/up`.
      mkdir -p "${{targets.destdir}}"/usr/bin
      install -Dm755 $(go env GOPATH)/bin/up "${{targets.destdir}}"/usr/bin/up

  - uses: strip

update:
  enabled: true
  github:
    identifier: upbound/up
    strip-prefix: v
